name: testEnvironment deploy(tab,smartphone)

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  # ジョブの名前
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Version
        run: docker version

      - name: Build Docker Images
        run: docker compose build

      - name: Start Docker Containers
        run: docker compose up -d

      # composer インストール
      - name: composer install
        run: docker compose exec app composer install

      # Envoy インストール
      - name: Envoy install
        run: composer require laravel/envoy:1.6.1

      # laravel envoyを利用してEC2に接続、デプロイ
      - name: EC2 connection
        env:
          PRIVATE_KEY: ${{ secrets.TEST_PRIVATE_KEY }}
          USER_NAME: ${{ secrets.TEST_USER_NAME }}
          HOST_NAME: ${{ secrets.TEST_HOST_NAME }}
        run: |
          # 秘密鍵をgithubactionsにコピー
          mkdir -p /home/runner/.ssh
          touch /home/runner/.ssh/id_rsa
          echo "$TEST_PRIVATE_KEY" > /home/runner/.ssh/id_rsa
          # パーミッション変更
          chmod 600 /home/runner/.ssh/id_rsa
          ssh-keyscan ${{ secrets.TEST_HOST_NAME }} >> ~/.ssh/known_hosts

      # Envoy 実行
      - name: Envoy
        run: ./vendor/bin/envoy run testdeploy